-- Show warnings after every statement.
\W


-- Disable foreign key checks so tables can be dropped/created in any order.
SET FOREIGN_KEY_CHECKS = 0;


-- Concepts file.
DROP TABLE IF EXISTS concepts;
CREATE TABLE concepts (
    CONCEPTID NUMERIC(18) UNSIGNED NOT NULL PRIMARY KEY,
    CONCEPTSTATUS INT UNSIGNED NOT NULL,
    FULLYSPECIFIEDNAME VARCHAR(255) NOT NULL,
    CTV3ID VARCHAR(100) NOT NULL,
    SNOMEDID VARCHAR(100) NOT NULL,
    ISPRIMITIVE BOOLEAN NOT NULL
) CHARACTER SET utf8;

LOAD DATA LOCAL INFILE 'Terminology/Content/sct1_Concepts_${editionType}_${editionLabel}_${editionVersion}.txt' INTO TABLE concepts LINES TERMINATED BY '\r\n' IGNORE 1 LINES
(@CONCEPTID,@CONCEPTSTATUS,@FULLYSPECIFIEDNAME,@CTV3ID,@SNOMEDID,@ISPRIMITIVE)
SET CONCEPTID = @CONCEPTID,
CONCEPTSTATUS = @CONCEPTSTATUS,
FULLYSPECIFIEDNAME = @FULLYSPECIFIEDNAME,
CTV3ID = @CTV3ID,
SNOMEDID = @SNOMEDID,
ISPRIMITIVE = @ISPRIMITIVE;


-- Descriptions file.
DROP TABLE IF EXISTS descriptions;
CREATE TABLE descriptions (
    DESCRIPTIONID NUMERIC(18) UNSIGNED NOT NULL PRIMARY KEY,
    DESCRIPTIONSTATUS INT UNSIGNED NOT NULL,
    CONCEPTID NUMERIC(18) UNSIGNED NOT NULL,
    TERM VARCHAR(255) NOT NULL,
    INITIALCAPITALSTATUS INT UNSIGNED NOT NULL,
    DESCRIPTIONTYPE VARCHAR(100) NOT NULL,
    LANGUAGECODE VARCHAR(5) NOT NULL,
    FOREIGN KEY (CONCEPTID) REFERENCES concepts(CONCEPTID)
) CHARACTER SET utf8;

LOAD DATA LOCAL INFILE 'Terminology/Content/sct1_Descriptions_en_${editionLabel}_${editionVersion}.txt' INTO TABLE descriptions LINES TERMINATED BY '\r\n' IGNORE 1 LINES
(@DESCRIPTIONID,@DESCRIPTIONSTATUS,@CONCEPTID,@TERM,@INITIALCAPITALSTATUS,@DESCRIPTIONTYPE,@LANGUAGECODE)
SET DESCRIPTIONID = @DESCRIPTIONID,
DESCRIPTIONSTATUS = @DESCRIPTIONSTATUS,
CONCEPTID = @CONCEPTID,
TERM = @TERM,
INITIALCAPITALSTATUS = @INITIALCAPITALSTATUS,
DESCRIPTIONTYPE = @DESCRIPTIONTYPE,
LANGUAGECODE = @LANGUAGECODE;


-- Relationships file.
DROP TABLE IF EXISTS relationships;
CREATE TABLE relationships (
    RELATIONSHIPID NUMERIC(18) UNSIGNED NOT NULL PRIMARY KEY,
    CONCEPTID1 NUMERIC(18) UNSIGNED NOT NULL,
    RELATIONSHIPTYPE NUMERIC(18) UNSIGNED NOT NULL,
    CONCEPTID2 NUMERIC(18) UNSIGNED NOT NULL,
    CHARACTERISTICTYPE INT UNSIGNED NOT NULL,
    REFINABILITY INT UNSIGNED NOT NULL,
    RELATIONSHIPGROUP INT UNSIGNED NOT NULL,
    FOREIGN KEY (CONCEPTID1) REFERENCES concepts(CONCEPTID),
    FOREIGN KEY (RELATIONSHIPTYPE) REFERENCES concepts(CONCEPTID),
    FOREIGN KEY (CONCEPTID2) REFERENCES concepts(CONCEPTID)
) CHARACTER SET utf8;

LOAD DATA LOCAL INFILE 'Terminology/Content/sct1_Relationships_${editionType}_${editionLabel}_${editionVersion}.txt' INTO TABLE relationships LINES TERMINATED BY '\r\n' IGNORE 1 LINES
(@RELATIONSHIPID,@CONCEPTID1,@RELATIONSHIPTYPE,@CONCEPTID2,@CHARACTERISTICTYPE,@REFINABILITY,@RELATIONSHIPGROUP)
SET RELATIONSHIPID = @RELATIONSHIPID,
CONCEPTID1 = @CONCEPTID1,
RELATIONSHIPTYPE = @RELATIONSHIPTYPE,
CONCEPTID2 = @CONCEPTID2,
CHARACTERISTICTYPE = @CHARACTERISTICTYPE,
REFINABILITY = @REFINABILITY,
RELATIONSHIPGROUP = @RELATIONSHIPGROUP;


-- Component History file.
DROP TABLE IF EXISTS componenthistory;
CREATE TABLE componenthistory (
    COMPONENTID NUMERIC(18) UNSIGNED NOT NULL,
    RELEASEVERSION DATE NOT NULL,
    CHANGETYPE INT UNSIGNED NOT NULL,
    STATUS INT UNSIGNED NOT NULL,
    REASON VARCHAR(255)
) CHARACTER SET utf8;

LOAD DATA LOCAL INFILE 'Terminology/History/sct1_ComponentHistory_${editionType}_${editionLabel}_${editionVersion}.txt' INTO TABLE componenthistory LINES TERMINATED BY '\r\n' IGNORE 1 LINES
(@COMPONENTID,@RELEASEVERSION,@CHANGETYPE,@STATUS,@REASON)
SET COMPONENTID = @COMPONENTID,
RELEASEVERSION = @RELEASEVERSION,
CHANGETYPE = @CHANGETYPE,
STATUS = @STATUS,
REASON = @REASON;


-- References file.
-- (Cannot name simply 'references' because that is a reserved keyword in MySQL.)
DROP TABLE IF EXISTS referencescore;
CREATE TABLE referencescore (
    COMPONENTID NUMERIC(18) UNSIGNED NOT NULL,
    REFERENCETYPE INT UNSIGNED NOT NULL,
    REFERENCEDID NUMERIC(18) UNSIGNED NOT NULL
) CHARACTER SET utf8;

LOAD DATA LOCAL INFILE 'Terminology/History/sct1_References_${editionType}_${editionLabel}_${editionVersion}.txt' INTO TABLE referencescore LINES TERMINATED BY '\r\n' IGNORE 1 LINES
(@COMPONENTID,@REFERENCETYPE,@REFERENCEDID)
SET COMPONENTID = @COMPONENTID,
REFERENCETYPE = @REFERENCETYPE,
REFERENCEDID = @REFERENCEDID;


-- CrossMapSets ICD9 file.
DROP TABLE IF EXISTS crossmapsetsicd9;
CREATE TABLE crossmapsetsicd9 (
    MAPSETID NUMERIC(18) UNSIGNED NOT NULL PRIMARY KEY,
    MAPSETNAME VARCHAR(255) NOT NULL,
    MAPSETTYPE INT UNSIGNED NOT NULL,
    MAPSETSCHEMEID VARCHAR(255) NOT NULL,
    MAPSETSCHEMENAME VARCHAR(255) NOT NULL,
    MAPSETSCHEMEVERSION VARCHAR(255) NOT NULL,
    MAPSETREALMID NUMERIC(18) UNSIGNED,
    MAPSETSEPARATOR CHAR(1) NOT NULL,
    MAPSETRULETYPE INT UNSIGNED
) CHARACTER SET utf8;

LOAD DATA LOCAL INFILE 'Maps/ICD9/der1_CrossMapSets_ICD9_${editionLabel}_${editionVersion}.txt' INTO TABLE crossmapsetsicd9 LINES TERMINATED BY '\r\n' IGNORE 1 LINES
(@MAPSETID,@MAPSETNAME,@MAPSETTYPE,@MAPSETSCHEMEID,@MAPSETSCHEMENAME,@MAPSETSCHEMEVERSION,@MAPSETREALMID,@MAPSETSEPARATOR,@MAPSETRULETYPE)
SET MAPSETID = @MAPSETID,
MAPSETNAME = @MAPSETNAME,
MAPSETTYPE = @MAPSETTYPE,
MAPSETSCHEMEID = @MAPSETSCHEMEID,
MAPSETSCHEMENAME = @MAPSETSCHEMENAME,
MAPSETSCHEMEVERSION = @MAPSETSCHEMEVERSION,
MAPSETSEPARATOR = @MAPSETSEPARATOR,
MAPSETRULETYPE = NULLIF(@MAPSETRULETYPE,'');


-- CrossMapTargets ICD9 file.
DROP TABLE IF EXISTS crossmaptargetsicd9;
CREATE TABLE crossmaptargetsicd9 (
    TARGETID NUMERIC(18) UNSIGNED NOT NULL PRIMARY KEY,
    TARGETSCHEMEID VARCHAR(255) NOT NULL,
    TARGETCODES VARCHAR(100) NOT NULL,
    TARGETRULE VARCHAR(4000),
    TARGETADVICE VARCHAR(4000)
) CHARACTER SET utf8;

LOAD DATA LOCAL INFILE 'Maps/ICD9/der1_CrossMapTargets_ICD9_${editionLabel}_${editionVersion}.txt' INTO TABLE crossmaptargetsicd9 LINES TERMINATED BY '\r\n' IGNORE 1 LINES
(@TARGETID,@TARGETSCHEMEID,@TARGETCODES,@TARGETRULE,@TARGETADVICE)
SET TARGETID = @TARGETID,
TARGETSCHEMEID = @TARGETSCHEMEID,
TARGETCODES = @TARGETCODES,
TARGETRULE = @TARGETRULE,
TARGETADVICE = @TARGETADVICE;


-- CrossMaps ICD9 file.
DROP TABLE IF EXISTS crossmapsicd9;
CREATE TABLE crossmapsicd9 (
    MAPSETID NUMERIC(18) UNSIGNED NOT NULL,
    MAPCONCEPTID NUMERIC(18) UNSIGNED NOT NULL,
    MAPOPTION INT UNSIGNED NOT NULL,
    MAPPRIORITY INT UNSIGNED NOT NULL,
    MAPTARGETID NUMERIC(18) UNSIGNED NOT NULL,
    MAPRULE VARCHAR(4000) NOT NULL,
    MAPADVICE VARCHAR(4000) NOT NULL,
    FOREIGN KEY (MAPSETID) REFERENCES crossmapsetsicd9(MAPSETID),
    FOREIGN KEY (MAPCONCEPTID) REFERENCES concepts(CONCEPTID),
    FOREIGN KEY (MAPTARGETID) REFERENCES crossmaptargetsicd9(TARGETID)
) CHARACTER SET utf8;

LOAD DATA LOCAL INFILE 'Maps/ICD9/der1_CrossMaps_ICD9_${editionLabel}_${editionVersion}.txt' INTO TABLE crossmapsicd9 LINES TERMINATED BY '\r\n' IGNORE 1 LINES
(@MAPSETID,@MAPCONCEPTID,@MAPOPTION,@MAPPRIORITY,@MAPTARGETID,@MAPRULE,@MAPADVICE)
SET MAPSETID = @MAPSETID,
MAPCONCEPTID = @MAPCONCEPTID,
MAPOPTION = @MAPOPTION,
MAPPRIORITY = @MAPPRIORITY,
MAPTARGETID = @MAPTARGETID,
MAPRULE = @MAPRULE,
MAPADVICE = @MAPADVICE;


-- CrossMapSets ICDO file.
DROP TABLE IF EXISTS crossmapsetsicdo;
CREATE TABLE crossmapsetsicdo (
    MAPSETID NUMERIC(18) UNSIGNED NOT NULL PRIMARY KEY,
    MAPSETNAME VARCHAR(255) NOT NULL,
    MAPSETTYPE INT UNSIGNED NOT NULL,
    MAPSETSCHEMEID VARCHAR(255) NOT NULL,
    MAPSETSCHEMENAME VARCHAR(255) NOT NULL,
    MAPSETSCHEMEVERSION YEAR NOT NULL,
    MAPSETREALMID NUMERIC(18) UNSIGNED,
    MAPSETSEPARATOR CHAR(1) NOT NULL,
    MAPSETRULETYPE INT UNSIGNED
) CHARACTER SET utf8;

LOAD DATA LOCAL INFILE 'Maps/ICDO/der1_CrossMapSets_ICDO_${editionLabel}_${editionVersion}.txt' INTO TABLE crossmapsetsicdo LINES TERMINATED BY '\r\n' IGNORE 1 LINES
(@MAPSETID,@MAPSETNAME,@MAPSETTYPE,@MAPSETSCHEMEID,@MAPSETSCHEMENAME,@MAPSETSCHEMEVERSION,@MAPSETREALMID,@MAPSETSEPARATOR,@MAPSETRULETYPE)
SET MAPSETID = @MAPSETID,
MAPSETNAME = @MAPSETNAME,
MAPSETTYPE = @MAPSETTYPE,
MAPSETSCHEMEID = @MAPSETSCHEMEID,
MAPSETSCHEMENAME = @MAPSETSCHEMENAME,
MAPSETSCHEMEVERSION = @MAPSETSCHEMEVERSION,
MAPSETSEPARATOR = @MAPSETSEPARATOR,
MAPSETRULETYPE = NULLIF(@MAPSETRULETYPE,'');


-- CrossMapTargets ICDO file.
DROP TABLE IF EXISTS crossmaptargetsicdo;
CREATE TABLE crossmaptargetsicdo (
    TARGETID NUMERIC(18) UNSIGNED NOT NULL PRIMARY KEY,
    TARGETSCHEMEID VARCHAR(255),
    TARGETCODES VARCHAR(100) NOT NULL,
    TARGETRULE VARCHAR(4000),
    TARGETADVICE VARCHAR(4000)
) CHARACTER SET utf8;

LOAD DATA LOCAL INFILE 'Maps/ICDO/der1_CrossMapTargets_ICDO_${editionLabel}_${editionVersion}.txt' INTO TABLE crossmaptargetsicdo LINES TERMINATED BY '\r\n' IGNORE 1 LINES
(@TARGETID,@TARGETSCHEMEID,@TARGETCODES,@TARGETRULE,@TARGETADVICE)
SET TARGETID = @TARGETID,
TARGETSCHEMEID = @TARGETSCHEMEID,
TARGETCODES = @TARGETCODES,
TARGETRULE = @TARGETRULE,
TARGETADVICE = @TARGETADVICE;


-- CrossMaps ICDO file.
DROP TABLE IF EXISTS crossmapsicdo;
CREATE TABLE crossmapsicdo (
    MAPSETID NUMERIC(18) UNSIGNED NOT NULL,
    MAPCONCEPTID NUMERIC(18) UNSIGNED NOT NULL,
    MAPOPTION INT UNSIGNED NOT NULL,
    MAPPRIORITY INT UNSIGNED NOT NULL,
    MAPTARGETID NUMERIC(18) UNSIGNED NOT NULL,
    MAPRULE VARCHAR(4000) NOT NULL,
    MAPADVICE VARCHAR(4000) NOT NULL,
    FOREIGN KEY (MAPSETID) REFERENCES crossmapsetsicdo(MAPSETID),
    FOREIGN KEY (MAPCONCEPTID) REFERENCES concepts(CONCEPTID),
    FOREIGN KEY (MAPTARGETID) REFERENCES crossmaptargetsicdo(TARGETID)
) CHARACTER SET utf8;

LOAD DATA LOCAL INFILE 'Maps/ICDO/der1_CrossMaps_ICDO_${editionLabel}_${editionVersion}.txt' INTO TABLE crossmapsicdo LINES TERMINATED BY '\r\n' IGNORE 1 LINES
(@MAPSETID,@MAPCONCEPTID,@MAPOPTION,@MAPPRIORITY,@MAPTARGETID,@MAPRULE,@MAPADVICE)
SET MAPSETID = @MAPSETID,
MAPCONCEPTID = @MAPCONCEPTID,
MAPOPTION = @MAPOPTION,
MAPPRIORITY = @MAPPRIORITY,
MAPTARGETID = @MAPTARGETID,
MAPRULE = @MAPRULE,
MAPADVICE = @MAPADVICE;


-- Subsets en-GB file.
DROP TABLE IF EXISTS subsetsengb;
CREATE TABLE subsetsengb (
    SUBSETID NUMERIC(18) UNSIGNED NOT NULL PRIMARY KEY,
    SUBSETORIGINALID NUMERIC(18) UNSIGNED NOT NULL,
    SUBSETVERSION INT UNSIGNED NOT NULL,
    SUBSETNAME VARCHAR(255) NOT NULL,
    SUBSETTYPE INT UNSIGNED NOT NULL,
    LANGUAGECODE CHAR(5) NOT NULL,
    REALMID NUMERIC(18) UNSIGNED,
    CONTEXTID NUMERIC(18) UNSIGNED
) CHARACTER SET utf8;

LOAD DATA LOCAL INFILE 'Subsets/Language-en-GB/der1_Subsets_en-GB_${editionLabel}_${editionVersion}.txt' INTO TABLE subsetsengb LINES TERMINATED BY '\r\n' IGNORE 1 LINES
(@SUBSETID,@SUBSETORIGINALID,@SUBSETVERSION,@SUBSETNAME,@SUBSETTYPE,@LANGUAGECODE,@REALMID,@CONTEXTID)
SET SUBSETID = @SUBSETID,
SUBSETORIGINALID = @SUBSETORIGINALID,
SUBSETVERSION = @SUBSETVERSION,
SUBSETNAME = @SUBSETNAME,
SUBSETTYPE = @SUBSETTYPE,
LANGUAGECODE = @LANGUAGECODE,
REALMID = @REALMID,
CONTEXTID = @CONTEXTID;


-- SubsetMembers en-GB file.
DROP TABLE IF EXISTS subsetmembersengb;
CREATE TABLE subsetmembersengb (
    SUBSETID NUMERIC(18) UNSIGNED NOT NULL,
    MEMBERID NUMERIC(18) UNSIGNED NOT NULL,
    MEMBERSTATUS INT UNSIGNED NOT NULL,
    LINKEDID VARCHAR(100),
    FOREIGN KEY (SUBSETID) REFERENCES subsetsengb(SUBSETID),
    FOREIGN KEY (MEMBERID) REFERENCES descriptions(DESCRIPTIONID)
) CHARACTER SET utf8;

LOAD DATA LOCAL INFILE 'Subsets/Language-en-GB/der1_SubsetMembers_en-GB_${editionLabel}_${editionVersion}.txt' INTO TABLE subsetmembersengb LINES TERMINATED BY '\r\n' IGNORE 1 LINES
(@SUBSETID,@MEMBERID,@MEMBERSTATUS,@LINKEDID)
SET SUBSETID = @SUBSETID,
MEMBERID = @MEMBERID,
MEMBERSTATUS = @MEMBERSTATUS,
LINKEDID = @LINKEDID;


-- Subsets en-US file.
DROP TABLE IF EXISTS subsetsenus;
CREATE TABLE subsetsenus (
    SUBSETID NUMERIC(18) UNSIGNED NOT NULL PRIMARY KEY,
    SUBSETORIGINALID NUMERIC(18) UNSIGNED NOT NULL,
    SUBSETVERSION INT UNSIGNED NOT NULL,
    SUBSETNAME VARCHAR(255) NOT NULL,
    SUBSETTYPE INT UNSIGNED NOT NULL,
    LANGUAGECODE CHAR(5) NOT NULL,
    REALMID NUMERIC(18) UNSIGNED,
    CONTEXTID NUMERIC(18) UNSIGNED
) CHARACTER SET utf8;

LOAD DATA LOCAL INFILE 'Subsets/Language-en-US/der1_Subsets_en-US_${editionLabel}_${editionVersion}.txt' INTO TABLE subsetsenus LINES TERMINATED BY '\r\n' IGNORE 1 LINES
(@SUBSETID,@SUBSETORIGINALID,@SUBSETVERSION,@SUBSETNAME,@SUBSETTYPE,@LANGUAGECODE,@REALMID,@CONTEXTID)
SET SUBSETID = @SUBSETID,
SUBSETORIGINALID = @SUBSETORIGINALID,
SUBSETVERSION = @SUBSETVERSION,
SUBSETNAME = @SUBSETNAME,
SUBSETTYPE = @SUBSETTYPE,
LANGUAGECODE = @LANGUAGECODE,
REALMID = @REALMID,
CONTEXTID = @CONTEXTID;


-- SubsetMembers en-US file.
DROP TABLE IF EXISTS subsetmembersenus;
CREATE TABLE subsetmembersenus (
    SUBSETID NUMERIC(18) UNSIGNED NOT NULL,
    MEMBERID NUMERIC(18) UNSIGNED NOT NULL,
    MEMBERSTATUS INT UNSIGNED NOT NULL,
    LINKEDID VARCHAR(100),
    FOREIGN KEY (SUBSETID) REFERENCES subsetsenus(SUBSETID),
    FOREIGN KEY (MEMBERID) REFERENCES descriptions(DESCRIPTIONID)
) CHARACTER SET utf8;

LOAD DATA LOCAL INFILE 'Subsets/Language-en-US/der1_SubsetMembers_en-US_${editionLabel}_${editionVersion}.txt' INTO TABLE subsetmembersenus LINES TERMINATED BY '\r\n' IGNORE 1 LINES
(@SUBSETID,@MEMBERID,@MEMBERSTATUS,@LINKEDID)
SET SUBSETID = @SUBSETID,
MEMBERID = @MEMBERID,
MEMBERSTATUS = @MEMBERSTATUS,
LINKEDID = @LINKEDID;


-- Subsets NonHuman file.
-- Commented out - no more non-human file
--DROP TABLE IF EXISTS subsetsnonhuman;
--CREATE TABLE subsetsnonhuman (
--    SUBSETID NUMERIC(18) UNSIGNED NOT NULL PRIMARY KEY,
--    SUBSETORIGINALID NUMERIC(18) UNSIGNED NOT NULL,
--    SUBSETVERSION INT UNSIGNED NOT NULL,
--    SUBSETNAME VARCHAR(255) NOT NULL,
--    SUBSETTYPE INT UNSIGNED NOT NULL,
--    LANGUAGECODE CHAR(5) NOT NULL,
--    REALMID NUMERIC(18) UNSIGNED,
--    CONTEXTID NUMERIC(18) UNSIGNED
--) CHARACTER SET utf8;

--LOAD DATA LOCAL INFILE 'Subsets/NonHumanSubset/der1_Subsets_NonHuman_${editionLabel}_${editionVersion}.txt' INTO TABLE subsetsnonhuman LINES TERMINATED BY '\r\n' IGNORE 1 LINES
--(@SUBSETID,@SUBSETORIGINALID,@SUBSETVERSION,@SUBSETNAME,@SUBSETTYPE,@LANGUAGECODE,@REALMID,@CONTEXTID)
--SET SUBSETID = @SUBSETID,
--SUBSETORIGINALID = @SUBSETORIGINALID,
--SUBSETVERSION = @SUBSETVERSION,
--SUBSETNAME = @SUBSETNAME,
--SUBSETTYPE = @SUBSETTYPE,
--LANGUAGECODE = @LANGUAGECODE,
--REALMID = @REALMID,
--CONTEXTID = @CONTEXTID;


-- SubsetMembers NonHuman file.
--DROP TABLE IF EXISTS subsetmembersnonhuman;
--CREATE TABLE subsetmembersnonhuman (
--    SUBSETID NUMERIC(18) UNSIGNED NOT NULL,
--    MEMBERID NUMERIC(18) UNSIGNED NOT NULL,
--    MEMBERSTATUS INT UNSIGNED NOT NULL,
--    LINKEDID VARCHAR(100),
--    FOREIGN KEY (SUBSETID) REFERENCES subsetsnonhuman(SUBSETID),
--    FOREIGN KEY (MEMBERID) REFERENCES concepts(CONCEPTID)
--) CHARACTER SET utf8;

--LOAD DATA LOCAL INFILE 'Subsets/NonHumanSubset/der1_SubsetMembers_NonHuman_${editionLabel}_${editionVersion}.txt' INTO TABLE subsetmembersnonhuman LINES TERMINATED BY '\r\n' IGNORE 1 LINES
--(@SUBSETID,@MEMBERID,@MEMBERSTATUS,@LINKEDID)
--SET SUBSETID = @SUBSETID,
--MEMBERID = @MEMBERID,
--MEMBERSTATUS = @MEMBERSTATUS,
--LINKEDID = @LINKEDID;


-- Subsets VTMVMP file.
DROP TABLE IF EXISTS subsetsvtmvmp;
CREATE TABLE subsetsvtmvmp (
    SUBSETID NUMERIC(18) UNSIGNED NOT NULL PRIMARY KEY,
    SUBSETORIGINALID NUMERIC(18) UNSIGNED NOT NULL,
    SUBSETVERSION INT UNSIGNED NOT NULL,
    SUBSETNAME VARCHAR(255) NOT NULL,
    SUBSETTYPE INT UNSIGNED NOT NULL,
    LANGUAGECODE CHAR(5) NOT NULL,
    REALMID NUMERIC(18) UNSIGNED,
    CONTEXTID NUMERIC(18) UNSIGNED
) CHARACTER SET utf8;

LOAD DATA LOCAL INFILE 'Subsets/VTMVMP/der1_Subsets_VTMVMP_${editionLabel}_${editionVersion}.txt' INTO TABLE subsetsvtmvmp LINES TERMINATED BY '\r\n' IGNORE 1 LINES
(@SUBSETID,@SUBSETORIGINALID,@SUBSETVERSION,@SUBSETNAME,@SUBSETTYPE,@LANGUAGECODE,@REALMID,@CONTEXTID)
SET SUBSETID = @SUBSETID,
SUBSETORIGINALID = @SUBSETORIGINALID,
SUBSETVERSION = @SUBSETVERSION,
SUBSETNAME = @SUBSETNAME,
SUBSETTYPE = @SUBSETTYPE,
LANGUAGECODE = @LANGUAGECODE,
REALMID = @REALMID,
CONTEXTID = @CONTEXTID;


-- SubsetMembers VTMVMP file.
DROP TABLE IF EXISTS subsetmembersvtmvmp;
CREATE TABLE subsetmembersvtmvmp (
    SUBSETID NUMERIC(18) UNSIGNED NOT NULL,
    MEMBERID NUMERIC(18) UNSIGNED NOT NULL,
    MEMBERSTATUS INT UNSIGNED NOT NULL,
    LINKEDID VARCHAR(100),
    FOREIGN KEY (SUBSETID) REFERENCES subsetsvtmvmp(SUBSETID),
    FOREIGN KEY (MEMBERID) REFERENCES concepts(CONCEPTID)
) CHARACTER SET utf8;

LOAD DATA LOCAL INFILE 'Subsets/VTMVMP/der1_SubsetMembers_VTMVMP_${editionLabel}_${editionVersion}.txt' INTO TABLE subsetmembersvtmvmp LINES TERMINATED BY '\r\n' IGNORE 1 LINES
(@SUBSETID,@MEMBERID,@MEMBERSTATUS,@LINKEDID)
SET SUBSETID = @SUBSETID,
MEMBERID = @MEMBERID,
MEMBERSTATUS = @MEMBERSTATUS,
LINKEDID = @LINKEDID;


-- Restore foreign key checks to enforce referential integrity.
SET FOREIGN_KEY_CHECKS = 1;
