WHENEVER SQLERROR EXIT -1
SET ECHO ON

CREATE INDEX x_comphist_componentid ON componenthistory(COMPONENTID)
PCTFREE 10 COMPUTE STATISTICS;

CREATE INDEX x_references_componentid on references(COMPONENTID)
PCTFREE 10 COMPUTE STATISTICS;

CREATE INDEX x_references_referenceid on references(REFERENCEDID)
PCTFREE 10 COMPUTE STATISTICS;
